name: poe-writer # you probably want to 'snapcraft register <name>'
version: '2.2.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: A distraction free writing app # 79 char long summary
description: |
  Poe is a distraction free writing suite built by writers, for writers.
  It contains all sorts of features to help you write that masterpiece,
  but it also stays out of your way. 

icon: icon.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core20

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
